name: 'Customer Repo CI/CD Workflow'
on:
  pull_request:
    branches:
      - 'main'
jobs:
  algosec-risk-analysis-action:
     name: 'Algosec Risk Analysis Test Job'
     runs-on: ubuntu-latest
     steps:
      - name: debug
        uses: hmarr/debug-action@v2
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: 'Algosec Risk Analysis Action'
        uses: alonnalgo/action-test@v0.0.38
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          RA_API_URL: ${{ secrets.RA_API_URL }}
          AWS_S3: ${{ secrets.AWS_S3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

