name: 'Customer Repo CI/CD'
on:
  pull_request:
    branches:
      - 'main'
jobs:
  algosec-risk-analysis-job:
     name: 'Algosec Risk Analysis Job'
     runs-on: ubuntu-latest
     steps:
        - name: 'Algosec Risk Analysis Action'
          run: alonnalgo/risk-analysis-action@0.0.53
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_SHA: ${{ github.sha }}
            GITHUB_WORKSPACE: ${{ github.workspace }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_REGION: us-west-2
            AWS_S3: ${{ secrets.AWS_S3 }}
            RA_API_URL: ${{ secrets.RA_API_URL }}

          
          
          
         

